//! Generic store-level key/value metadata.
//!
//! Not demo-specific in spirit — any feature needing a single durable flag
//! on the store itself (rather than a per-row column) can use this table.
//! Today only `lopi demo`'s fixture generator writes to it, via the
//! `"synthetic"` key that [`MemoryStore::is_synthetic`] reads back.

use anyhow::Result;

use super::MemoryStore;

/// The `store_metadata` key `lopi demo`'s fixture generator sets to mark a
/// store as fabricated. See [`MemoryStore::is_synthetic`].
const SYNTHETIC_KEY: &str = "synthetic";

impl MemoryStore {
    /// Set a store-level metadata key/value pair (upsert).
    ///
    /// # Errors
    /// Returns `Err` if the database write fails.
    pub async fn set_metadata(&self, key: &str, value: &str) -> Result<()> {
        sqlx::query(
            "INSERT INTO store_metadata (key, value) VALUES (?1, ?2) \
             ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        )
        .bind(key)
        .bind(value)
        .execute(&self.write_pool)
        .await?;
        Ok(())
    }

    /// Read a store-level metadata value, `None` if unset.
    ///
    /// # Errors
    /// Returns `Err` if the database query fails.
    pub async fn get_metadata(&self, key: &str) -> Result<Option<String>> {
        let row: Option<(String,)> =
            sqlx::query_as("SELECT value FROM store_metadata WHERE key = ?1")
                .bind(key)
                .fetch_optional(&self.read_pool)
                .await?;
        Ok(row.map(|(value,)| value))
    }

    /// Whether this store was generated by `lopi demo`'s fixture generator
    /// (the `"synthetic"` metadata key is `"true"`). This is the single
    /// source of truth every rendering surface should check before
    /// presenting demo data as real — driven by the store itself, not a
    /// runtime flag, so opening a demo store through any code path still
    /// announces itself. Defaults to `false` (including on error, logged
    /// via `tracing::warn!` — a store lookup failure must never be
    /// silently read as "real").
    ///
    /// Never returns `Err` — a lookup failure is a fallback (default to
    /// "not synthetic"), and per this crate's no-silent-failures rule a
    /// swallowed error is always logged via `tracing::warn!` rather than
    /// bubbled up or dropped.
    pub async fn is_synthetic(&self) -> Result<bool> {
        match self.get_metadata(SYNTHETIC_KEY).await {
            Ok(value) => Ok(value.as_deref() == Some("true")),
            Err(e) => {
                tracing::warn!(error = %e, "is_synthetic lookup failed — defaulting to false");
                Ok(false)
            }
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    async fn store() -> MemoryStore {
        MemoryStore::open_in_memory().await.unwrap()
    }

    #[tokio::test]
    async fn set_then_get_round_trips() {
        let s = store().await;
        s.set_metadata("foo", "bar").await.unwrap();
        assert_eq!(s.get_metadata("foo").await.unwrap().as_deref(), Some("bar"));
    }

    #[tokio::test]
    async fn get_on_unset_key_returns_none() {
        let s = store().await;
        assert_eq!(s.get_metadata("nope").await.unwrap(), None);
    }

    #[tokio::test]
    async fn set_upserts_existing_key() {
        let s = store().await;
        s.set_metadata("foo", "one").await.unwrap();
        s.set_metadata("foo", "two").await.unwrap();
        assert_eq!(s.get_metadata("foo").await.unwrap().as_deref(), Some("two"));
    }

    #[tokio::test]
    async fn is_synthetic_false_on_fresh_store() {
        let s = store().await;
        assert!(!s.is_synthetic().await.unwrap());
    }

    #[tokio::test]
    async fn is_synthetic_true_after_set() {
        let s = store().await;
        s.set_metadata("synthetic", "true").await.unwrap();
        assert!(s.is_synthetic().await.unwrap());
    }

    #[tokio::test]
    async fn is_synthetic_false_for_other_values() {
        let s = store().await;
        s.set_metadata("synthetic", "false").await.unwrap();
        assert!(!s.is_synthetic().await.unwrap());
        s.set_metadata("synthetic", "garbage").await.unwrap();
        assert!(!s.is_synthetic().await.unwrap());
    }
}
