#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use super::*;

#[test]
fn docs_paths_match_markdown_and_docs_dir() {
    assert!(is_docs_path("research.md"));
    assert!(is_docs_path("NOTES.MD"));
    assert!(is_docs_path("docs/architecture.rst"));
    assert!(is_docs_path("nested/docs/plan.txt"));
    assert!(is_docs_path("README"));
    assert!(is_docs_path("path/to/CHANGELOG"));
}

#[test]
fn non_docs_paths_are_rejected() {
    assert!(!is_docs_path("src/main.rs"));
    assert!(!is_docs_path("Cargo.toml"));
    assert!(!is_docs_path("Cargo.lock"));
    assert!(!is_docs_path("package.json"));
    assert!(!is_docs_path("scripts/build.sh"));
}

#[test]
fn lockfile_paths_are_recognized() {
    assert!(is_lockfile_path("Cargo.lock"));
    assert!(is_lockfile_path("nested/Cargo.lock"));
    assert!(is_lockfile_path("package-lock.json"));
    assert!(is_lockfile_path("yarn.lock"));
    assert!(is_lockfile_path("pnpm-lock.yaml"));
    assert!(!is_lockfile_path("Cargo.toml"));
    assert!(!is_lockfile_path("src/main.rs"));
}

#[test]
fn skip_build_check_when_nothing_changed() {
    // The regression this guards: an attempt that halted before writing
    // anything used to fall through to a real `cargo test`/`clippy` run
    // against a target repo with no compilable code.
    assert!(should_skip_build_check(&[]));
}

/// The regression this guards: a docs-only attempt (`research.md`) whose
/// working tree also carries a `Cargo.lock` regenerated by the Scorer's
/// own earlier `cargo test`/`clippy` invocation used to read as
/// source-touching — whole-tree `git status` can't distinguish "the
/// attempt changed this" from "a prior probe run touched this" — forcing
/// a real build check against a target repo whose broken/empty scaffold
/// guarantees a false `pass=0%`.
#[test]
fn skip_build_check_when_docs_and_lockfile_only() {
    assert!(should_skip_build_check(&[
        (true, "research.md".to_string()),
        (false, "Cargo.lock".to_string()),
    ]));
}

#[test]
fn skip_build_check_when_only_docs_changed() {
    assert!(should_skip_build_check(&[
        (true, "research.md".to_string()),
        (false, "docs/notes.md".to_string()),
    ]));
}

#[test]
fn does_not_skip_build_check_when_source_changed() {
    assert!(!should_skip_build_check(&[
        (true, "research.md".to_string()),
        (false, "src/main.rs".to_string()),
    ]));
}

#[test]
fn porcelain_line_parses_untracked() {
    assert_eq!(
        parse_porcelain_line("?? research.md"),
        Some((true, "research.md".to_string()))
    );
}

#[test]
fn porcelain_line_parses_modified_tracked() {
    assert_eq!(
        parse_porcelain_line(" M src/main.rs"),
        Some((false, "src/main.rs".to_string()))
    );
}

#[test]
fn porcelain_line_parses_rename_to_new_path() {
    assert_eq!(
        parse_porcelain_line("R  old.md -> new.md"),
        Some((false, "new.md".to_string()))
    );
}

#[test]
fn parse_diff_lines_sums_insertions_and_deletions() {
    assert_eq!(
        parse_diff_lines(" 3 files changed, 42 insertions(+), 7 deletions(-)"),
        49
    );
}

#[test]
fn parse_diff_lines_handles_empty_stat() {
    assert_eq!(parse_diff_lines(""), 0);
}

/// Init a real git repo at `repo` with one committed file, then modify
/// `tracked_file` (writing `content`) so `should_skip_build_check`
/// sees a real, non-docs, non-lockfile source change and `score()`
/// actually runs detection instead of taking the "nothing changed" exit.
fn init_repo_with_tracked_change(repo: &Path, tracked_file: &str, content: &str) {
    std::process::Command::new("git")
        .args(["init", "-q"])
        .current_dir(repo)
        .status()
        .expect("git init");
    std::process::Command::new("git")
        .args(["config", "user.email", "t@t.com"])
        .current_dir(repo)
        .status()
        .expect("git config email");
    std::process::Command::new("git")
        .args(["config", "user.name", "t"])
        .current_dir(repo)
        .status()
        .expect("git config name");
    std::fs::write(repo.join(".gitkeep"), "").expect("write .gitkeep");
    std::process::Command::new("git")
        .args(["add", "."])
        .current_dir(repo)
        .status()
        .expect("git add");
    std::process::Command::new("git")
        .args(["commit", "-q", "-m", "init"])
        .current_dir(repo)
        .status()
        .expect("git commit");
    std::fs::write(repo.join(tracked_file), content).expect("write tracked file");
}

/// KT-2.1 (Sprint F2) — reproduces the pre-fix defect this repo's own
/// scorer had: a repo with no recognized manifest (no `Cargo.toml`,
/// `package.json`, pytest/go/gradle/maven marker) and a real tracked
/// source change scored `test_pass_rate = 1.0` — a perfect score having
/// run zero tests. See `.konjo/killtests/F2/KT-2.1.md` for the recorded
/// pre-fix output this test was built from.
#[tokio::test]
async fn unrecognized_stack_no_longer_reports_a_perfect_pass() {
    let dir = tempfile::tempdir().expect("tempdir");
    let repo = dir.path();
    init_repo_with_tracked_change(repo, "app.py", "print('hi')\ndef foo(): pass\n");

    let score = Scorer::new(repo).score().await.expect("score");

    // Pre-fix (see KT-2.1.md): `test_pass_rate == 1.0`, `passed() ==
    // true` — a passing score having run nothing. Post-Phase-2, an
    // unevaluable repo must never read as a pass, and must carry a
    // stated reason rather than a silent restriction.
    assert!(
        !score.passed(),
        "an unrecognized stack must never score as passing"
    );
    assert!(
        score.unevaluated_reason.is_some(),
        "the unevaluable case must carry a stated reason, not just a low number"
    );
}

/// Phase 1 verify — a pytest repo with a failing test scores as failing
/// (not as an unrecognized-stack pass). Real `pytest` binary, real repo,
/// per the anti-mocking rule for E2E coverage.
#[tokio::test]
async fn pytest_repo_with_a_failing_test_scores_as_failing() {
    let dir = tempfile::tempdir().expect("tempdir");
    let repo = dir.path();
    std::fs::write(repo.join("pyproject.toml"), "[project]\nname = \"fixture\"\n")
        .expect("write pyproject.toml");
    init_repo_with_tracked_change(repo, "test_sample.py", "def test_fails():\n    assert False\n");

    let score = Scorer::new(repo).score().await.expect("score");

    assert!(!score.passed(), "a failing pytest run must not pass");
    assert!(score.unevaluated_reason.is_none(), "pytest was detected and ran — not unevaluated");
    assert_eq!(score.test_pass_rate, 0.0);
}

/// Phase 1 verify — a Go repo with a failing test scores as failing.
/// Real `go test` binary, real repo.
#[tokio::test]
async fn go_repo_with_a_failing_test_scores_as_failing() {
    let dir = tempfile::tempdir().expect("tempdir");
    let repo = dir.path();
    std::fs::write(repo.join("go.mod"), "module fixture\n\ngo 1.21\n").expect("write go.mod");
    init_repo_with_tracked_change(
        repo,
        "fixture_test.go",
        "package fixture\n\nimport \"testing\"\n\nfunc TestFails(t *testing.T) {\n\tt.Fatal(\"boom\")\n}\n",
    );

    let score = Scorer::new(repo).score().await.expect("score");

    assert!(!score.passed(), "a failing go test run must not pass");
    assert!(score.unevaluated_reason.is_none(), "go.mod was detected and ran — not unevaluated");
    assert_eq!(score.test_pass_rate, 0.0);
}
