//! Demo-mode read/refuse helpers shared by handlers that must never scan
//! the real filesystem or accept a mutation against a synthetic store. See
//! `docs/adr/0001-demo-mode-and-measurement.md`.

use super::AppState;
use axum::{
    http::StatusCode,
    response::{IntoResponse, Json},
};
use serde_json::json;

/// Whether `state`'s store was generated by `lopi demo` — the single check
/// every demo-aware handler runs before rendering real-looking data or
/// accepting a mutation.
pub(super) async fn is_demo(state: &AppState) -> bool {
    state.store.is_synthetic().await.unwrap_or(false)
}

/// A `403` refusal body for a mutation attempted against a synthetic store.
/// `action` names what was refused, e.g. `"create a task"`.
pub(super) fn refuse_mutation(action: &str) -> impl IntoResponse {
    (
        StatusCode::FORBIDDEN,
        Json(json!({
            "error": format!("demo mode is read-only — refusing to {action}"),
            "synthetic": true
        })),
    )
}
